import Head from "next/head";
import styles from "./contact.module.scss";
import Image from "next/image";

export default function Contact() {
  const isProd = process.env.NODE_ENV === "production";
  const basePath = isProd ? "/hungtse-next" : "";

  return (
    <div className={`container`}>
      <Head>
        <title>聯絡我們 | 竑澤實業股份有限公司</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.banner}>
        <Image
          src={basePath + "/image/comp3/5 聯絡我們.png"}
          alt="banner"
          layout="fill"
          objectFit="cover"
          quality={100}
        />
        <div className={styles.desc}>
          <h2>廠區介紹</h2>
        </div>
      </div>

      <main></main>
    </div>
  );
}
