import Head from "next/head";

export default function Contact() {
  return (
    <div className={`container`}>
      <Head>
        <title>竑澤實業股份有限公司</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>contact</main>
    </div>
  );
}
