import Head from "next/head";

export default function Factory() {
  return (
    <div className={`container`}>
      <Head>
        <title>廠區介紹 | 竑澤實業股份有限公司</title>
        <meta name="description" content="Generated by create next app" />
      </Head> 

      <main></main>
    </div>
  );
}
