import Head from "next/head";
// import Image from 'next/image'
import styles from "../styles/Home.module.css";

import Footer from "../components/TheFooter";

export default function Home() {
  var a = [styles.container, "container"].join(" ");
  return (
    <div className={a}>
      <Head>
        <title>竑澤實業股份有限公司</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>lorem*1000</main>

      <Footer></Footer>
    </div>
  );
}
