import Head from "next/head";
import Image from "next/image";
import styles from "./products.module.scss";

// import Header from "../components/TheHeader";
// import Footer from "../components/TheFooter";

export default function Products() {
  const images = {
    mainImage:
      "https://images.pexels.com/photos/957024/forest-trees-perspective-bright-957024.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    otherImages: [
      {
        image:
          "https://images.pexels.com/photos/1408221/pexels-photo-1408221.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1F",
        name: "棉",
      },
      {
        image:
          "https://images.pexels.com/photos/1408221/pexels-photo-1408221.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1F",
        name: "尼龍",
      },
      {
        image:
          "https://images.pexels.com/photos/1408221/pexels-photo-1408221.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1F",
        name: "人造絲",
      },
    ],
  };
  const productsType = [
    {
      name: "寢具",
      ...images,
    },
    {
      name: "浴袍",
      ...images,
    },
    {
      name: "傢飾",
      ...images,
    },
    {
      name: "成衣",
      ...images,
    },
    {
      name: "醫療",
      ...images,
    },
    {
      name: "迷彩",
      ...images,
    },
  ];

  // console.log(productsType);

  return (
    <div>
      <Head>
        <title>竑澤實業股份有限公司</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.banner}>
        <div className={styles.desc}>
          <h3>產品項目</h3>
        </div>
      </div>

      <main>
        <div className={styles.title} style={{ marginTop: 33 + "px" }}>
          布種列表
        </div>
        <div className={styles.section}>
          <Image
            src="/布種一覽-42.png"
            alt="布種一覽"
            width={1200}
            height={285}
          />
        </div>
        <div className={styles.title} style={{ marginTop: 33 + "px" }}>
          布料用途
        </div>
        <div className={`${styles.section} `}>
          <div className="product-type-choose white-section">
            {productsType.map((item, index) => {
              return <button key={index}>{item.name}</button>;
            })}
          </div>
          <div className="Thumbnail white-section">
            {productsType.map((item, index) => {
              return (
                <div key={index}>
                  <div className="product-type-name">{item.name}</div>
                  <div className="product-type-Thumbnail">
                    <div className="product-type-Thumbnail-main">
                      <Image
                        src={item.mainImage}
                        alt=""
                        width={1145}
                        height={796}
                      />
                    </div>
                    <div
                      className="product-type-Thumbnail-other"
                      style={{
                        width: "100%",
                        height: "250px",
                      }}
                    >
                      {item.otherImages.map((subItem, index) => {
                        return (
                          <div key={index}>
                            <Image src={subItem.image} alt="" layout="fill" />
                            <span>{subItem.name}</span>
                          </div>
                        );
                      })}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </div>
  );
}
