name: Generate static file and push to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci

      - name: Build
        run: |
          # git branch
          npm run static
          # ls
          # git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b gh-pages origin/gh-pages
          git pull

          mkdir other
          mv * other/
          mv other/out .
          rm -rf todelete
          cp -r ./out/* ./

          git add .
          git commit -m "generated"
          git push
